language: java

jdk:
  - oraclejdk7
#  - openjdk7
#  - openjdk6

env:
  global:
    - secure: "pmNBqCAW1rc4WKHEmnroZNwAMus18K1VWhRYwt+CN0acH8griJp612tjwWcI\n9XkZcSPR0CJx1TZqGDZZTFH44Pkm6ELU1kc54xtJR6WMXnubEVoEom0tcv/1\nNyzxv9UFJfaNgaTESww+OXSlO9wQre5ZS0/wn2xrz0+twtOPYDU="
    - secure: "CZ9mejMLJdrh+a5TFXsNSiYyK9K/zNYOtubv2sPq1OEGhuohdUfLtdsk7bK9\nQcIlhZjrE5Q/wVgjZcFsnVpKhnUSRLC7sTOh6tu08EwpNtnNLl5AeUztOMCs\nxhG5H7jDu9uEH81WDZnIuK4Zq4qxXx523rnqQfk4DsTCKLVh9jI="

before_install:
  - git submodule update --init --recursive

before_script:
  - python etc/travis-sonatype.py

script: python etc/travis-build.py --settings ~/.m2/sonatype.xml

after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:cobertura
