#
#    Copyright 2011-2020 the original author or authors.
#
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of the GNU General Public License
#    as published by the Free Software Foundation; either version 2
#    of the License, or (at your option) any later version.
#
#    You may obtain a copy of the License at
#
#       https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#

name: Java Integration Tests Maven 3.5.0

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Integration Tests Maven 3.5.0

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Load Maven 3.5.0
        run: ./mvnw -B -V org.apache.maven.plugins:maven-wrapper-plugin:3.2.0:wrapper -Dmaven=3.5.0 --no-transfer-progress
      - name: Build Setup
        run: ./mvnw -B -V clean install -Dmaven.min-version=3.5.0
      - name: Integration Test with Maven
        run: ./mvnw -B -V -Prun-its clean install -Dmaven.min-version=3.5.0
