#
#    Copyright 2011-2021 the original author or authors.
#
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of the GNU General Public License
#    as published by the Free Software Foundation; either version 2
#    of the License, or (at your option) any later version.
#
#    You may obtain a copy of the License at
#
#       https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#

name: Java Integration Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        java: [21]
      fail-fast: false
      max-parallel: 4
    name: Integration Tests

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: zulu
      - name: Build Setup
        run: ./mvnw clean install
      - name: Integration Test with Maven
        run: ./mvnw -Prun-it clean install -B
